using _10xPhysio.Server.Models.Database;
using _10xPhysio.Server.Models.Dto.Common;

namespace _10xPhysio.Server.Models.Dto.Visits
{
    /// <summary>
    /// Represents the full visit payload returned across create, update, and get endpoints.
    /// </summary>
    public class VisitDto
    {
        /// <summary>
        /// Gets or sets the visit identifier (<see cref="Visit.Id"/>).
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the patient identifier (<see cref="Visit.PatientId"/>).
        /// </summary>
        public Guid PatientId { get; set; }

        /// <summary>
        /// Gets or sets the visit date/time (<see cref="Visit.VisitDate"/>).
        /// </summary>
        public DateTimeOffset VisitDate { get; set; }

        /// <summary>
        /// Gets or sets the optional interview content.
        /// </summary>
        public string? Interview { get; set; }

        /// <summary>
        /// Gets or sets the optional description content.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the optional recommendations.
        /// </summary>
        public string? Recommendations { get; set; }

        /// <summary>
        /// Gets or sets whether the recommendations were generated by AI.
        /// </summary>
        public bool RecommendationsGeneratedByAi { get; set; }

        /// <summary>
        /// Gets or sets the timestamp at which recommendations were generated, if applicable.
        /// </summary>
        public DateTimeOffset? RecommendationsGeneratedAt { get; set; }

        /// <summary>
        /// Gets or sets the creation timestamp (<see cref="Visit.CreatedAt"/>).
        /// </summary>
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the last update timestamp (<see cref="Visit.UpdatedAt"/>).
        /// </summary>
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets the weak ETag derived from <see cref="UpdatedAt"/>.
        /// </summary>
        public string ETag { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the AI generation count used in visit listings.
        /// </summary>
        public int? AiGenerationCount { get; set; }

        /// <summary>
        /// Gets or sets the latest AI generation identifier (if any) used in visit detail responses.
        /// </summary>
        public Guid? LatestAiGenerationId { get; set; }

        /// <summary>
        /// Materializes a visit DTO from a database entity with optional AI metadata augmentation.
        /// </summary>
        /// <param name="visit">Visit entity backing the DTO.</param>
        /// <param name="aiGenerationCount">Optional AI generation count aggregated from <see cref="VisitAiGeneration"/>.</param>
        /// <param name="latestAiGenerationId">Optional latest AI generation identifier.</param>
        /// <returns>Hydrated visit DTO.</returns>
        public static VisitDto FromEntity(
            Visit visit,
            int? aiGenerationCount = null,
            Guid? latestAiGenerationId = null)
        {
            ArgumentNullException.ThrowIfNull(visit);

            return new VisitDto
            {
                Id = visit.Id,
                PatientId = visit.PatientId,
                VisitDate = visit.VisitDate,
                Interview = visit.Interview,
                Description = visit.Description,
                Recommendations = visit.Recommendations,
                RecommendationsGeneratedByAi = visit.RecommendationsGeneratedByAi,
                RecommendationsGeneratedAt = visit.RecommendationsGeneratedAt,
                CreatedAt = visit.CreatedAt,
                UpdatedAt = visit.UpdatedAt,
                ETag = WeakEtag.FromTimestamp(visit.UpdatedAt),
                AiGenerationCount = aiGenerationCount,
                LatestAiGenerationId = latestAiGenerationId
            };
        }
    }
}
